<?php
declare(strict_types=1);

// UrlShortener SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

UrlShortenerUtility::setRegistrar(function (UrlShortenerUtility $u): void {
    $u->clean = [UrlShortenerClean::class, 'call'];
    $u->done = [UrlShortenerDone::class, 'call'];
    $u->make_error = [UrlShortenerMakeError::class, 'call'];
    $u->feature_add = [UrlShortenerFeatureAdd::class, 'call'];
    $u->feature_hook = [UrlShortenerFeatureHook::class, 'call'];
    $u->feature_init = [UrlShortenerFeatureInit::class, 'call'];
    $u->fetcher = [UrlShortenerFetcher::class, 'call'];
    $u->make_fetch_def = [UrlShortenerMakeFetchDef::class, 'call'];
    $u->make_context = [UrlShortenerMakeContext::class, 'call'];
    $u->make_options = [UrlShortenerMakeOptions::class, 'call'];
    $u->make_request = [UrlShortenerMakeRequest::class, 'call'];
    $u->make_response = [UrlShortenerMakeResponse::class, 'call'];
    $u->make_result = [UrlShortenerMakeResult::class, 'call'];
    $u->make_point = [UrlShortenerMakePoint::class, 'call'];
    $u->make_spec = [UrlShortenerMakeSpec::class, 'call'];
    $u->make_url = [UrlShortenerMakeUrl::class, 'call'];
    $u->param = [UrlShortenerParam::class, 'call'];
    $u->prepare_auth = [UrlShortenerPrepareAuth::class, 'call'];
    $u->prepare_body = [UrlShortenerPrepareBody::class, 'call'];
    $u->prepare_headers = [UrlShortenerPrepareHeaders::class, 'call'];
    $u->prepare_method = [UrlShortenerPrepareMethod::class, 'call'];
    $u->prepare_params = [UrlShortenerPrepareParams::class, 'call'];
    $u->prepare_path = [UrlShortenerPreparePath::class, 'call'];
    $u->prepare_query = [UrlShortenerPrepareQuery::class, 'call'];
    $u->graphql_body = [UrlShortenerGraphql::class, 'body'];
    $u->graphql_errors = [UrlShortenerGraphql::class, 'errors'];
    $u->result_basic = [UrlShortenerResultBasic::class, 'call'];
    $u->result_body = [UrlShortenerResultBody::class, 'call'];
    $u->result_headers = [UrlShortenerResultHeaders::class, 'call'];
    $u->transform_request = [UrlShortenerTransformRequest::class, 'call'];
    $u->transform_response = [UrlShortenerTransformResponse::class, 'call'];
});
